config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
  end

  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_rich_text :description

  validates_presence_of :name, :subtitle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :authenticate_user!
  # before_action :verify_admin_permission

  # def verify_admin_permission
  #   redirect_to root_path unless current_user.admin?
  # end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :set_product, only: %i[show edit update destroy]

    def index
      @q = Product.ransack(params[:q])
      @products = @q.result
    end

    def show
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_product_path(@product)
      else
        render :new
      end
    end

    def edit
    end

    def update
      @product.update(product_params)
      if @product.save
        redirect_to admin_product_path(@product)
      else
        render :edit
      end
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path, notice: 'Produto deletado com sucesso'
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :subtitle, :description, :price, :quantity, :active)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @products = Product.where(active: true)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @q = Product.ransack(params[:q])
    @products = @q.result
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>

  <%= f.input :name,
      label: "Nome do produto" %>

  <%= f.input :subtitle,
      label: "Subtítulo do produto" %>

  <%= f.input :price,
      as: :numeric,
      label: "Valor de cobrança",
      placeholder: "" %>

  <%= f.input :quantity,
      as: :numeric,
      label: "Quantidade em estoque" %>

  <%= f.collection_radio_buttons  :active,
                                  [[true, 'SIM'] , [false, 'NÃO']],
                                  :first, :last,
                                  label: "Deixar produto visível para venda?" %>

  <%= f.rich_text_area :description,
      class: "form_with_rich_text",
      required: true,
      label: false,
      placeholder: "Descrição do produto" %>

  <%= f.submit "Salvar produto" %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editar produto <%= @product.name %> (<%= @product.id %>)</h1>
  <%= link_to "< Voltar", admin_product_path(@product) %>
  <%= render "form" %>
</div>

app/views/admin/products/index.html.erb
<h2>Produtos</h2>
<%= link_to "Criar novo produto", new_admin_product_path %>

<table class="table table-striped table-custom">
  <tr>
    <th>Nome</th>
    <th>Subtítulo</th>
    <th>Preço</th>
    <th>Quantidade</th>
    <th>Ativo</th>
    <th>Ações</th>
  </tr>
<% if @products.empty? || @products.nil? %>
  <tr>
    <td colspan='6' class='text-center'>Nenhum produto foi criado</td>
  </tr>
<% else %>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.subtitle %></td>
      <td><%= number_to_currency(product.price/100, unit: "R$", separator: ",", delimiter: ".") %></td>
      <td><%= product.quantity %></td>
      <td><%= product.active? ? "Ativado" : "Desativado" %></td>
      <td class="border-secondary border-right text-center">
        <%= link_to admin_product_path(product) do %>
          <i class="far fa-eye"></i>
        <% end %>
        <%= link_to edit_admin_product_path(product) do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to admin_product_path(product), method: :delete, data: { confirm: 'Deseja deletar esse produto?' } do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/admin/products/new.html.erb
<h1>Criar novo produto</h1>
  <%= link_to "< Voltar", admin_products_path %>
  <%= render "form" %>
</div>

app/views/admin/products/show.html.erb
<h1><%= @product.name %></h1>

<ul>
  <%= link_to "< Voltar", admin_products_path  %>
  <%= link_to "Editar produto", edit_admin_product_path(@product) %>
</ul>

<ul>
  <li><strong>Nome:</strong> <%= @product.name %></li>
  <li><strong>Subtítulo:</strong> <%= @product.subtitle %></li>
  <li><strong>Descrição:</strong> <%= @product.description %></li>
  <li><strong>Preço:</strong> <%= number_to_currency(@product.price/100, unit: "R$", separator: ",", delimiter: ".") %></li>
  <li><strong>Quantidade em estoque:</strong> <%= @product.quantity %></li>
  <li><strong>Está ativo?</strong> <%= @product.active? ? "Ativado" : "Desativado" %></li>
<ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercadoGoblin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/_about.html.erb
<div class="bg-gray-900">
  <h2>Sobre mim</h2>

  <p>Conhecida pelo nome artístico de Milady Mori, sou formada em Design de Moda no Centro Universitário Belas Artes de São Paulo. Trabalho como figurista, artesã, costuro e bordo.</p>
</div>

app/views/pages/_contact.html.erb
<div class="bg-gray-900">
  <h2>Contato</h2>

</div>

app/views/pages/_portfolio.html.erb
<div class="bg-gray-900">
  <h2>Portfólio</h2>
  <p>Alguns dos projetos em que atuei<p>
  <button>Veja todos os trabalhos</button>
</div>

app/views/pages/_shop.html.erb
<div class="bg-dark-gray">
  <h2>Mercado Goblin</h2>
  <p>Minhas criações que estão disponíveis para encomenda<p>
  <button>Conheça minha loja</button>
</div>

app/views/pages/_timeline.html.erb
<div class="timeline">
  <h2>Minha Jornada</h2>
  <ul>
    <li>
      <h4>Título da minha experiência</h4>
      <p>(Agosto/2020 - Dezembro/2020)</p>
      <span>#moda</span>
      <p>Descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz.</p>
    </li>
    <li>
      <h4>Título da minha experiência</h4>
      <p>(Agosto/2020 - Dezembro/2020)</p>
      <p>Descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz.</p>
    </li>
    <li>
      <h4>Título da minha experiência</h4>
      <p>(Agosto/2020 - Dezembro/2020)</p>
      <p>Descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz.</p>
    </li>
    <li>
      <h4>Título da minha experiência</h4>
      <p>(Agosto/2020 - Dezembro/2020)</p>
      <p>Descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz, descrição do que eu fiz.</p>
    </li>
  </ul>
</div>

app/views/pages/home.html.erb
<section class="home">
</section>

<%= render "about" %>
<%= render "timeline" %>
<%= render "portfolio" %>
<%= render "shop" %>
<%= render "contact" %>

app/views/products/index.html.erb
<div class="features-container">
  <section class="features">
    <h2>Features</h2>
    <div class="card">
      <img src="/images/photos/mercado-goblin-1.jpeg">
      <h4>Teste</h4>
      <p>Minha descrição aqui</p>
    </div>
    <div class="card">
      <img src="/images/photos/mercado-goblin-1.jpeg">
      <h4>Teste</h4>
      <p>Minha descrição aqui</p>
    </div>
    <div class="card">
      <img src="/images/photos/mercado-goblin-1.jpeg">
      <h4>Teste</h4>
      <p>Minha descrição aqui</p>
    </div>
  <section>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<ul>
  <%= link_to "< Voltar", root_path  %>
</ul>

<ul>
  <li><strong>Nome:</strong> <%= @product.name %></li>
  <li><strong>Subtítulo:</strong> <%= @product.subtitle %></li>
  <li><strong>Descrição:</strong> <%= @product.description %></li>
  <li><strong>Preço:</strong> <%= number_to_currency(@product.price/100, unit: "R$", separator: ",", delimiter: ".") %></li>
  <li><strong>Quantidade em estoque:</strong> <%= @product.quantity %></li>
  <li><strong>Está ativo?</strong> <%= @product.active? ? "Ativado" : "Desativado" %></li>
<ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="nav">
  <div class="logo">
    <li><%= link_to "MORI'S STUDIO", root_path, class: "amarante" %></li>
  </div>

  <div id="navWeb" class="main_list">
    <ul>
      <li><a href="#">Sobre</a></li>
      <li><a href="#">Timeline</a></li>
      <li><a href="#">Contato</a></li>
      <li><a href="#">Portfólio</a></li>
      <li><a href="#">Mercado Goblin</a></li>
      <% if user_signed_in? %>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete, class: "amarante" %></li>
      <% else %>
        <li><%= link_to "Entrar", new_user_session_path, class: "amarante" %></li>
      <% end %>
    </ul>
  </div>

  <div id="navMobile">
    <button class="nav-toggle">
      <i class="fas fa-bars" style="color:white;"></i>
    </button>

    <div id='navMobileMenu'>
      <ul class='navbar-nav d-flex'>
        <li class='nav-item'>
          <li><a class="amarante" href="#">Sobre</a></li>
        </li>
        <li class='nav-item'>
          <li><a class="amarante" href="#">Timeline</a></li>
        </li>
        <li class='nav-item'>
          <li><a class="amarante" href="#">Contato</a></li>
        </li>
        <li class='nav-item'>
          <li><a class="amarante" href="#">Portfólio</a></li>
        </li>
        <li class='nav-item'>
          <li><a class="amarante" href="#">Mercado Goblin</a></li>
        </li>


        <li class='nav-item'>
          <% if user_signed_in? %>
            <li><%= link_to "Sair", destroy_user_session_path, method: :delete, class: "amarante" %></li>
          <% else %>
            <li><%= link_to "Entrar", new_user_session_path, class: "amarante" %></li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>